### ISSUE TITLE
createdeploymentgroup option -u

### ISSUE THREAD

**Issue by kkp1225** [IBM-UrbanCode/Informatica-UCD#18]
Hi,

Create Dynamic Deployment Group step cannot file Query.

createdeploymentgroup - p $groupname -t $dynamic -q $query.

I have tried the same command in commandline, same error "cannot file the query"

Below command is working with using the option -u to use Shared/Personal
createdeploymentgroup - p $groupname -t $dynamic -q $query -u Shared

Can we update this plugin to use this option ?

Thanks,
Kiran

**Comment by nhmathis** [comment]
Hi kkp1225,

This feature hasn't been added yet. If you would like to see this feature present in the plug-in, feel free to submit a pull request. But please note, we'll need to maintain past functionality. If you create a pull request, I'd be happy to walk you through the necessary changes. Otherwise, we'll get to this issue as soon as we can.

In the meantime, you can use the Run PMREP Command or a Shell step. Because this plugin is largely just a CLI wrapper, it would have nearly identical functionality.

**Comment by nhmathis** [comment]
Resolved in commit: 394d17d7a472a62ea23916170ef7d5b3bffc0eae

**Comment by nhmathis** [comment]
Resolved in release: https://github.com/IBM-UrbanCode/Informatica-UCD/releases/tag/24
