### ISSUE TITLE
deploy deployment group step error: couldn't connect to server

### ISSUE THREAD

**Issue by kkp1225** [IBM-UrbanCode/Informatica-UCD#20]
Hi,

I'm running the deploy deployment group step, It is failing with error: 

deploydpeloymentgroup -p groupname -c control file -r repository name -n userid -x pass -h hostname -o port
couldn't connect to server
failed to execute deploydeploymentgroup.

how to resolve this issue ? Please let me know your thoughts.

Thanks,
Kiran

**Comment by kkp1225** [comment]
I have tried manually running these commands but no luck.

connect -r rep_sit -n username -x ### -d DOM_SIT
deploydpeloymentgroup -p groupname -c control file -r repository rep_uat -n userid -x pass -h hostname -o port
couldn't connect to server
failed to execute deploydeploymentgroup.

deployment group is been created in rep_sit and deploy the group into rep_uat.

Please suggest me, if I'm missing any additional configuration here.

Thanks,
Kiran

**Comment by nhmathis** [comment]
Hi Kiran,

I would continue to use this [documentation](https://gerardnico.com/doc/powercenter/PC_861_CommandReference.pdf) to verify the attempted command. Note, the version this documentation provides may be different than the Informatica version you are using. However, it should provide a good baseline and identical descriptions.

If you can find a combination of commands that work, you can use a Shell step to implement them in your process or we can work with you and get them changes implemented into the plugin.

Since you are unable to connect to the server, I would recommend checking all connection settings. Running a simple `ping` command from your local computer to that host may be beneficial. Confirm that that runtime location of the `pmrep` cli has access to the host server and credentials are valid.

**Comment by kkp1225** [comment]
thank you for the details. this has been resolved after adding the server names to the INFRA domain file. You can close this request.

**Comment by fernandoalvescosta01** [comment]
Good afternoon, could you show how the domains.infa file was after including the data from the other domain?
