### ISSUE TITLE
Passing properties files

### ISSUE THREAD

**Issue by ghost** [IBM-UrbanCode/Informatica-UCD#6]
For the Informatica Import Objects, Is it possible at all to be able to pass a properties file containing Folder and Repository Mapping, along with the Conflict Resolution rules? Unfortunately I am not really a developer and while I do plan on learning Java and Groovy, I am not there yet.

**Comment by nhmathis** [comment]
Hi @crossbug,

At this time, the Informatica Import Objects does not support file input for Folder/Repository Mapping and Conflict Resolution. However, it would be relatively simple to implement. If you want to make the change and submit a pull request, I'd be happy to work with you to get it merged. The general outline would look something like...


~~~~
// import_objects.groovy
def repositoryMappingList = props['repositoryMappingList']
File temp = new File(repositoryMappingList)
if (temp.isFile()) {
    repositoryMappingList = temp.text
}
repositoryMappingList?.split('\n').each{...}
~~~~

Couple things to note: 
This snippet would be repeated for each of the three properties: folderMappingList, repositoryMappingList, and conflictResolutionList
The input would be the full file path or relative to the working directory. 
The input files would need to contain the same formatted data that you would otherwise enter in the textAreaBox itself.
The plugin.xml description and info.xml would need to be updated to reflect this change.

Feel free to poke around our [plugin developer site](https://developer.ibm.com/urbancode/plugins/development-community/) and [knowledge center](http://www.ibm.com/support/knowledgecenter/SS4GSP_6.1.3/com.ibm.udeploy.reference.doc/topics/reference_plugins_create.html) for helpful information on plugin development. 

If you are up to the task, try to update the plugin on your own! Otherwise, when I get some free time, I'll make the updates myself. Feel free to post any other questions!

-Nick

**Comment by ghost** [comment]
Hi Nick.


Thank you for reaching out. I have cloned the repo, created another branch and made the changes, but I do not have permissions to submit a pull request on this repository. Would you be kind enough to grant me access to make a pull request?


Thank you very much,


Joshua Sarnovsky


________________________________

**Comment by nhmathis** [comment]
Hey,

As far as I know, I am unable to stop anyone from creating a pull request. You should have the necessary permissions. What error are you receiving? 

-Nick

**Comment by nhmathis** [comment]
Code has been merged. Closing issue. 
Pull Request: #7
